"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const bunion_1 = require("bunion");
console.log('debug level is:', bunion_1.Level.DEBUG, typeof bunion_1.Level.DEBUG);
bunion_1.log.info('crescendo');
bunion_1.log.warn('foo');
const child = bunion_1.log.child().setLevel(bunion_1.Level.WARN).setFields({ a: 'moooo' }).addField('bar', 'mar');
child.setLevel('ERROR');
child.error('money');
exports.default = 'b';
