"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const bar_1 = require("./bar");
console.log('bar', bar_1.default);
const stream = require('stream');
const readable = new stream.Readable({
    read() {
    }
});
readable.on('data', () => console.log('data'));
process.nextTick(() => console.log('next tick'));
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
readable.push('foo');
